### ISSUE TITLE
add GitHub sponsors for contributing

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#102]

**Comment by YolineB** [comment]
Follow up with Reshama

**Comment by reshamas** [comment]
We can put this on hold.

**Comment by reshamas** [comment]
GitHub sponsors application submitted.

This is a preview of DU's profile:
https://github.com/sponsors/data-umbrella?preview=true

**Comment by reshamas** [comment]
GitHub sponsors is enabled for all repo's in this organization.
