### ISSUE TITLE
Update design for grid display

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#106]
@iliadeleon Can we:  
1. Add end date of event
2. Add location of event

Example of **online** event:  

<img width="293" alt="WBNLA_a" src="https://user-images.githubusercontent.com/2507232/187279100-98203450-b6ff-4bf0-aa11-597a451f4458.png">

---

Example of **location with a city**:  

<img width="293" alt="WBNLA_b" src="https://user-images.githubusercontent.com/2507232/187279109-35425c02-bf59-4b9a-9205-7414e6d7365f.png">

**Comment by iliadeleon** [comment]
@reshamas 
<img width="374" alt="EventCard" src="https://user-images.githubusercontent.com/88496806/187299945-1c16c236-dff0-4df3-bf5d-8bd7e86e855f.png">

**Comment by reshamas** [comment]
@iliadeleon 
Is this a 1-day event?
Wondering if we can update the design to add an end date.

**Comment by iliadeleon** [comment]
Oops I sent the one I didnt update the date. Heres a 2 day event, for example:
<img width="374" alt="Event Thumb" src="https://user-images.githubusercontent.com/88496806/187307716-345e9ed6-c354-4959-8dc6-8f00d6530be8.png">

**Comment by victoriaklo** [comment]
Designs have been updated, closing ticket
