### ISSUE TITLE
footer: add arrow indicating that page is outside of current website

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#108]
In the footer for "Data Umbrella", can we add an arrow pointing to 2 o'clock indicating it leads us out of the site?

example:  
https://www.pymc.io/welcome.html

<img width="195" alt="Screen Shot 2022-08-29 at 3 20 28 PM" src="https://user-images.githubusercontent.com/2507232/187281220-f0f14789-b3e4-4f0e-8763-efa4b25cc63a.png">

**Comment by reshamas** [comment]
Hi @Saige243 Thanks for doing this.  It looks good!

Can we also add that arrow to "Donate" on the footer since it is an external link?
I wonder if we should also do it for the header item "Data Umbrella" since it's also an external link?

**Comment by Saige243** [comment]
@reshamas that sounds fantastic! Donate sounds great and I think the header for Data Umbrella definitely needs it as well. I'll make a ticket and knock those out!!
