### ISSUE TITLE
Update design for list display

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#109]
For the list view, can we also add:  
- end date
- location

Example of events that span over two months:
"Sep x - Oct x, 2022"

Example:  
<img width="988" alt="list_view" src="https://user-images.githubusercontent.com/2507232/187282601-288255db-a097-4781-9198-72683cf156e4.png">

cc:  @iliadeleon

**Comment by iliadeleon** [comment]
@reshamas List view will have start - end date. Example:
<img width="504" alt="Screen Shot 2022-08-29 at 5 59 23 PM" src="https://user-images.githubusercontent.com/88496806/187306535-a44499de-9a5f-4cef-8171-ef778c03d895.png">
