### ISSUE TITLE
update grid view to have 4 cards per row

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#110]
Current grid view has 3 images per row.  Would it be better to have 4 or 5 cards per row?

Example:  

<img width="972" alt="Screen Shot 2022-08-29 at 3 32 24 PM" src="https://user-images.githubusercontent.com/2507232/187283176-3fd78659-5017-4ec7-b3d7-7f8092511123.png">

**Comment by YolineB** [comment]
@reshamas, @jtorreggiani  Would we still want to change the grid view?

**Comment by reshamas** [comment]
> @reshamas, @jtorreggiani Would we still want to change the grid view?

@YolineB Yes, it would be nice to see the 4 column view, it might be a cleaner look.
cc:  @symeneses

**Comment by Saige243** [comment]
PR here:
https://github.com/data-umbrella/event-board-web/pull/134#pullrequestreview-1171129114
