### ISSUE TITLE
Update favicon and title

### ISSUE THREAD

**Issue by symeneses** [data-umbrella/event-board-web#114]
At the moment, the favicon and title is the react  app default.

**Comment by reshamas** [comment]
When I bookmark it, this is what I see:
<img width="384" alt="Screen Shot 2022-09-02 at 11 43 55 AM" src="https://user-images.githubusercontent.com/2507232/188190614-1427c5e3-6770-4220-a54f-7c756f76062b.png">

Favicon:  we don't have a logo for the event board yet, so I guess we can use the Data Umbrella logo for now.
Text:  change "React App" to "Data Umbrella: Data Events Board"
Image:  figure out what to add ?

LinkedIn preview:  
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fevents.dataumbrella.org
<img width="487" alt="Screen Shot 2022-09-02 at 11 46 52 AM" src="https://user-images.githubusercontent.com/2507232/188191130-3d26108d-b357-4ef3-9245-d840bd768872.png">

Twitter preview:  
https://linkpreview.dev/?url=https%3A%2F%2Fevents.dataumbrella.org

<img width="469" alt="Screen Shot 2022-09-02 at 11 47 55 AM" src="https://user-images.githubusercontent.com/2507232/188191337-c4662ffa-f27a-4323-93d5-860ab49d4942.png">

**Comment by jtorreggiani** [comment]
@reshamas and @symeneses, I've updated the favicon and tab title. It looks like the full text Data Umbrella: Data Events Board seems to get cut off in the link preview tool. We may need to keep that text shorter. 

I'm looking into the getting the thumbnail to show up now.

**Comment by reshamas** [comment]
Hi @jtorreggiani 
Let's try this one:  Data Umbrella: Events Board
Hopefully that is shorter and fits.

**Comment by YolineB** [comment]
Looks to be implemented!
