### ISSUE TITLE
Colorfont and Background color is not consistent in dark mode

### ISSUE THREAD

**Issue by symeneses** [data-umbrella/event-board-web#115]
## Description

Using dark mode keeps the font black. 

I saw in #49 dark mode is not fully implemented. Would this be part of the Phase 1?

<img width="864" alt="grafik" src="https://user-images.githubusercontent.com/12284951/188139909-b4d66227-7e45-4132-84f2-f79fd997045b.png">

![grafik](https://user-images.githubusercontent.com/12284951/188141097-6e721298-2333-45e3-ab03-217d316b4670.png)

**Comment by YolineB** [comment]
Issue has been fixed.
