### ISSUE TITLE
Implement button register in event preview

### ISSUE THREAD

**Issue by symeneses** [data-umbrella/event-board-web#118]
## Description

Implement action in button `Register` in event preview.

**Comment by jtorreggiani** [comment]
@symeneses, @reshamas, updated the registration button take the user to the specific event url. One thing we should consider is that some of the URLs in the spreadsheet provided are the conference landing page not their registration page. We may want to consider have a separate registration_url attribute to differentiate. Going to close as the link is working now, but we will want to decide what URL we use on the backend.
