### ISSUE TITLE
Implement digest sign up page visual design

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#12]

**Comment by iliadeleon** [comment]
View of Weekly Digest page (7.26.22)
![Weekly Digest Sign Up a](https://user-images.githubusercontent.com/88496806/181050585-5174158a-1827-4100-b694-6479d0911275.png)

**Comment by jtorreggiani** [comment]
We implement the MVP visual design for this page. Going to close this issue and we can follow up for design polish in a separate issue.
