### ISSUE TITLE
(To be broken into two issues)Pagination and Map View

### ISSUE THREAD

**Issue by dashcraft** [data-umbrella/event-board-web#144]
Missing features need to be completed either before or directly after refactor work.

- [ ] Add map option to view options
- [ ] Map view missing
- [ ] Add pagination
- [ ] Show 9 search results, the rest to be accessed via page buttons at bottom
- [ ] Return 10 search results for mobile

**Comment by YolineB** [comment]
Issue has been broken up into two separate tickets, see issue #222 and issue #73
