### ISSUE TITLE
Implement basic form fields and post to API

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#18]

**Comment by iliadeleon** [comment]
View of Event Form (7.26.22)
![Event Form](https://user-images.githubusercontent.com/88496806/181044724-82ce3e64-d9b8-4597-82bd-72308a29b2fe.png)

**Comment by jtorreggiani** [comment]
This issue began as a placeholder to implement the event form. As part of our scaffolding work we have working form with the majority of the fields shown in the Figma design about. We've created a follow up issue https://github.com/data-umbrella/event-board-web/issues/33 to make updates to the layout. Closing this issue to keep things organized.
