### ISSUE TITLE
Search and Filters Mobile Version

### ISSUE THREAD

**Issue by YolineB** [data-umbrella/event-board-web#183]
Refactor events search/filter box for mobile version

**Comment by YolineB** [comment]
Refactor events search/filter box for mobile version
[Figma File](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A6573)

- [ ] Search box needs to be at top
- [ ] Grid row/columns need to be adjusted

**Comment by Saige243** [comment]
- Popular Searches will be ticketed out separately as it's not being tracked at the moment.

**Comment by Saige243** [comment]
All of these items (except for Popular Searches) have been fixed with prior tickets. Closing the issue.

**Comment by YolineB** [comment]
The remaining tasks have been moved to issue #366
