### ISSUE TITLE
Login page email URL: update copy

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#194]
Need to update copy:  
1.  Sender email address to update
2. Subject needs to be updated:  xxx
3. Copy needs to be updated:  xxxx

<img width="584" alt="Screen Shot 2022-09-15 at 9 35 14 AM" src="https://user-images.githubusercontent.com/2507232/190417891-00a6814e-02cd-43f1-8dbf-34a4dd6eaaa7.png">

**Comment by YolineB** [comment]
Follow up with Ilia to confirm implementation

**Comment by YolineB** [comment]
Email currently looks like image below, last to do item is updating the sender email address (should not be learn@specollective.org)

![image](https://user-images.githubusercontent.com/92892101/217304276-c9b6f804-59f9-4caa-a686-e69b87c31b83.png)

**Comment by reshamas** [comment]
@YolineB 
It is events@dataumbrella.org

I don't know if there is a configuration issue with this one.
cc:  @jtorreggiani

**Comment by reshamas** [comment]
This issue is resolved.

<img width="1032" alt="Screen Shot 2023-03-14 at 6 07 30 PM" src="https://user-images.githubusercontent.com/2507232/225153131-e05751b1-fb60-4948-a592-2023b3821642.png">
