### ISSUE TITLE
Welcome Bot: doesn't seem to be working

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#195]
This is in the `config.yml` file:
https://github.com/data-umbrella/event-board-web/blob/main/.github/config.yml

Example of where the Welcome bot works:  
https://github.com/data-umbrella/event-transcripts/tree/main/.github

**Comment by reshamas** [comment]
cc:  @symeneses

**Comment by YolineB** [comment]
Follow up with Reshama and confirm implementation

**Comment by reshamas** [comment]
The Welcome bot still doesn't work, and I don't know why.  It works on our other repos.

**Comment by reshamas** [comment]
I needed to install the bot on the repo.

Let's see if it will work, moving forward.
https://github.com/behaviorbot/welcome

**Comment by reshamas** [comment]
This should be working now.
