### ISSUE TITLE
Mobile Nav Not Scrolling

### ISSUE THREAD

**Issue by jackwkinsey** [data-umbrella/event-board-web#202]
## Overview

If you open the mobile nav and try to scroll, the body of the page scrolls instead of the nav bar.

https://user-images.githubusercontent.com/5323147/190678533-ab4a86d8-a321-4236-8297-33fd5f6087e3.mov

## Acceptance Criteria

- [ ] When user scrolls with the mobile nav open, the nav should scroll.
- [ ] When user scrolls with the mobile nav open, the background (area behind the nav) should not scroll.

**Comment by Saige243** [comment]
Should've caught that. Nice work!
