### ISSUE TITLE
fix link to SPECollective

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#217]
link here points to Data Umbrella, not SPECollective:
https://events.dataumbrella.org/about

**Comment by Rohanfizz** [comment]
Please assign this to me @reshamas :)

**Comment by reshamas** [comment]
Hi @Rohanfizz, you can leave a note here saying: "I am working on this."

We need to update our contributing guidelines so folks know that and also that a pull request should be submitted within two weeks or someone else can work on it.

**Comment by Rohanfizz** [comment]
Sure, will update contributing guidelines  too👍
