### ISSUE TITLE
Minor fixes on Sponsors Page

### ISSUE THREAD

**Issue by victoriaklo** [data-umbrella/event-board-web#223]
Audit: https://docs.google.com/spreadsheets/d/1mfn1s6-ncwnaIYpDfD0OH1md6Ni2YB38N_qeyBZQwR8/edit#gid=1849252639
Figma: https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A3712

- [ ] Image for CZI is cut off, make bigger with some padding
- [ ] Digital Ocean logo is getting lost in Dark mode, see if they have a dark mode version

**Comment by Rohanfizz** [comment]
#244 Fixes this
