### ISSUE TITLE
Clean up styles/  minor fixes on About Us Page

### ISSUE THREAD

**Issue by victoriaklo** [data-umbrella/event-board-web#226]
Figma: https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A3890
Audit: https://docs.google.com/spreadsheets/d/1mfn1s6-ncwnaIYpDfD0OH1md6Ni2YB38N_qeyBZQwR8/edit#gid=1849252639

- [x] Hyperlinks are green color instead of blue
- [x] SPEC's link goes to dataumbrella.org
- [x] Social links should open on new tab
- [x] Yoline and Ilia's github is not linked
- [x] On Mobile dark mode, looks like theres a layer over the DU/SPEC intros making it very hard to see logos and links
- [x] "We built this board" should be larger size texts

**Comment by Saige243** [comment]
lgtm!👍
