### ISSUE TITLE
Clean Up NavBar Styles

### ISSUE THREAD

**Issue by victoriaklo** [data-umbrella/event-board-web#228]
Audit: https://docs.google.com/spreadsheets/d/1mfn1s6-ncwnaIYpDfD0OH1md6Ni2YB38N_qeyBZQwR8/edit#gid=464070281
Figma: https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=663%3A2513

- [ ] Missing weekly digest link in navbar - Under Events dropdown, there should be "Weekly Digest" button. Follow up with Joe to see what this should be, since previous discussions mentioned that it will not be on a weekly cadence
- [ ] "Events" drop down option does not change color to DU purple when it's hovered
- [ ] "Sponsors" and "Data Umbrella" is missing hover color in darkmode

**Comment by Saige243** [comment]
🚀
