### ISSUE TITLE
Search Results View Option Buttons 

### ISSUE THREAD

**Issue by YolineB** [data-umbrella/event-board-web#231]
The visual design of the buttons to select Grid, List, Calendar, and Map views need the following update:

- [ ] Hover states with box-shadow: 3px 3px 4px 0px rgba(0, 0, 0, 0.25);
- [ ] Should reflect the color layout as seen in the figma snapshot: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/92892101/197912375-c405ff6a-2f53-46de-8a2d-fce9c2d46584.png">

Found in this file path: event-board-web/src/components/elements/SearchResultViewSelector.js

**Comment by Saige243** [comment]
🚀
