### ISSUE TITLE
sponsor logo for Digital Ocean is not viewable in dark mode

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#238]
For Digital Ocean logo, they do a have a white logo here:
https://github.com/data-umbrella/info/tree/master/sponsors/digital-ocean/PNG

Digital Ocean Style Guide is here:
https://doimages.nyc3.digitaloceanspaces.com/brand-styleguide.pdf

**Comment by Rohanfizz** [comment]
#244 Fixes this.

**Comment by reshamas** [comment]
Closed via #244.  Thanks @Rohanfizz.
