### ISSUE TITLE
Clean Up Contact Page

### ISSUE THREAD

**Issue by YolineB** [data-umbrella/event-board-web#243]
As per the [Figma](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A3680) file, the following changes need to be made in the Contact Page:

- [x] Code of Conduct should open to new tab
- [x] Code of Conduct should have white text in dark mode
- [x] Hover color on send button should have hover shadow box-shadow: 3px 3px 4px 0px 25%
- [x] On Click have white background, du-purple-500 border

**Comment by Saige243** [comment]
lgtm!
