### ISSUE TITLE
create folders for assets / images

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#247]
Right now, all the logos and images are in one folder:
https://github.com/data-umbrella/event-board-web/tree/main/src/assets

It would be a good idea to organize the images, because as time goes on, it will be really difficult to follow. Some suggestions for folders:
`/people`
`/sponsors`
`/du_sc_logos`   (Data Umbrella logos)
`/social_media`
`/eb_images` (event board images)
`/images`  (other images)

cc:  @jtorreggiani @dashcraft

**Comment by Rohanfizz** [comment]
I am working on this.

**Comment by Rohanfizz** [comment]
@reshamas  I've made these folders for the images, can you please tell me where should I put SPEC logos? Should I make a new folder? What should that folder's name be?
![image](https://user-images.githubusercontent.com/50175798/200516361-889cd072-62e0-41e2-9eed-78bf721b51ae.png)

**Comment by reshamas** [comment]
> @Rohanfizz @reshamas can we use snake case (_ underscores separating names) for folder names instead of kebab case (- hyphen separating names) and use camelcase for asset filenames
> 
> I also need to go through and make sure all the filenames are camelcased, that's a chore i can get put on the list for an RA to refactor.

@dashcraft That works for me.  Can we add that to the Contributing Guide, and add a section called "Best Practices" so contributors know about it?

**Comment by Rohanfizz** [comment]
> @Rohanfizz How about we rename "du-logos" to "du-sc-logos" (for Data Umbrella & Spec Collective) and put both orgs' logos in there?

Sure, will add it that way👍

**Comment by reshamas** [comment]
@jtorreggiani @dashcraft 
For this issue, should we create an issue called "best-practices"?
Or is there another label that is used in development for tasks such as "refactoring", etc?
