### ISSUE TITLE
Search Results Dates - Fix Date Order

### ISSUE THREAD

**Issue by iliadeleon** [data-umbrella/event-board-web#249]
In both List and Grid view, the results are coming in out of order. 
Example in List: Its Nov, Feb, Dec, Mar, Jan
Example in Grid: Its Nov, Feb, Nov, Dec...

<img width="1305" alt="Screen Shot 2022-11-03 at 1 41 49 PM" src="https://user-images.githubusercontent.com/88496806/199827219-202e6325-f4fc-4f01-96ad-6cf049d5dbf6.png">
<img width="1306" alt="Screen Shot 2022-11-03 at 1 42 06 PM" src="https://user-images.githubusercontent.com/88496806/199827263-06b02673-2726-4bf6-98c8-4a9078aa74e7.png">

**Comment by jtorreggiani** [comment]
@reshamas, I released a fix for the grid view sorry. Going to close this ticket and work on the list sort issues as part of [#332](https://github.com/data-umbrella/event-board-web/issues/332).
