### ISSUE TITLE
Sign in/Sign up - Fix sizes

### ISSUE THREAD

**Issue by iliadeleon** [data-umbrella/event-board-web#250]
The input fields are different sizes for these screens. Maybe we can follow the sign up one?

<img width="358" alt="Screen Shot 2022-11-03 at 4 45 14 PM" src="https://user-images.githubusercontent.com/88496806/199831012-492d2dab-e16c-4410-bb84-8a2d78b295d0.png">
<img width="447" alt="Screen Shot 2022-11-03 at 4 45 20 PM" src="https://user-images.githubusercontent.com/88496806/199831022-acdd5015-4f49-4b54-b0d2-52abe401bbb4.png">

**Comment by symeneses** [comment]
Working on this 🙋🏽‍♀️
