### ISSUE TITLE
Implement Popular Searches

### ISSUE THREAD

**Issue by Saige243** [data-umbrella/event-board-web#268]
Implement Popular Searches feature for the Search/Filter event component. 
[Figma Link](https://www.figma.com/file/rs7dsdmKlxdfuQ0wobp5B2/Data-Umbrella?node-id=1457%3A6573)

<img width="192" alt="Screen Shot 2022-12-01 at 9 45 17 AM" src="https://user-images.githubusercontent.com/2507232/205082352-dfd1ea45-e0a5-4d47-a96c-c809728e0239.png">

**Comment by YolineB** [comment]
Follow up with Reshama
