### ISSUE TITLE
Weekly Digest Screen subscribe/unsubscribe (guest user)

### ISSUE THREAD

**Issue by Saige243** [data-umbrella/event-board-web#271]
If user is not logged in/is a guest user, accept Weekly Digest submission with a "Thank you for subscribing!" confirmation.

**Comment by iliadeleon** [comment]
![Screen Shot 2022-11-14 at 4 38 20 PM](https://user-images.githubusercontent.com/88496806/201771493-681efb70-ca9a-47b2-8db4-a3c9e9bc6b3f.png)

**Comment by YolineB** [comment]
Duplicate of issue #270
