### ISSUE TITLE
List Search Results Labels

### ISSUE THREAD

**Issue by YolineB** [data-umbrella/event-board-web#273]
List search results should only show label as colored blocks:

Should be:
<img width="226" alt="image" src="https://user-images.githubusercontent.com/92892101/201789585-cab81ee7-6470-4569-9748-ef1d70fdd29d.png">

Old:
<img width="551" alt="image" src="https://user-images.githubusercontent.com/92892101/201789388-dcc3ea5f-c8f6-46d7-b94e-e89d751abcc6.png">

**Comment by reshamas** [comment]
@YolineB 
I think the current list view that has the full label on type of event looks good.  

@iliadeleon Should we update Figma for this?
