### ISSUE TITLE
Weekly Digest: Show unsubscribe button when user already has active subscription

### ISSUE THREAD

**Issue by dashcraft** [data-umbrella/event-board-web#280]
The current user object now has a new property called `weekly_digest`

This property is a boolean, when true, it means a user is already subscribed and on the weekly digest signup page
should be a link to unsubscribe

**Comment by Saige243** [comment]
Paused until we figure out how we want to structure the data model (unsubscribe by id or email, etc.)

**Comment by YolineB** [comment]
Closed due to duplication #270
