### ISSUE TITLE
Move sponsor logos (dark mode) into sponsor folder

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#300]
the dark/light logos for CZI and DO should be in the sponsors folder

<img width="595" alt="Screen Shot 2022-12-13 at 9 25 52 AM" src="https://user-images.githubusercontent.com/2507232/207359466-fdcda091-6ffd-445d-9aee-43768e0545bd.png">

**Comment by reshamas** [comment]
@SangamSwadiK 
Would you like to work on this one?

**Comment by YolineB** [comment]
Follow up with Reshama

**Comment by reshamas** [comment]
@YolineB I am labeling this issue "help wanted"

**Comment by reshamas** [comment]
This appears to be resolved.
