### ISSUE TITLE
Contact Us form: Agreeing to CoC should be required to submit form

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#303]
I submitted a test issue on the Contact Form, did not click on the CoC box, and it went through.
If agreeing to the CoC is required (as indicated by an *), then there should be a check there. 
https://events.dataumbrella.org/contact

**Comment by Rohanfizz** [comment]
I'll Pick this up :)

**Comment by YolineB** [comment]
@reshamas Besides the Code of Conduct, would we also like to have a check for the "reference" question on the contact page? So far there is also an asterisk for that section, but no validation. I can include that in the PR with the CoC check per your approval.

**Comment by reshamas** [comment]
@YolineB 
yes! that's a great idea. 

By the way, can we make that check box a bit larger? It's a bit small.
(I think you just made a similar change to the "Feature this event")

<img width="578" alt="Screen Shot 2023-01-27 at 11 54 41 AM" src="https://user-images.githubusercontent.com/2507232/215146718-096a7ad4-7f98-4feb-bd78-187ed807640f.png">

**Comment by YolineB** [comment]
@reshamas Thanks for confirming, and yes, I'll work on the tiny check box and tack that on to the PR.

**Comment by reshamas** [comment]
This seems to be resolved.
