### ISSUE TITLE
calendar is showing duplicate entries (ex: for Dec 2022)

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#304]
calendar is showing duplicate entries.

Example:  
<img width="1050" alt="Screen Shot 2022-12-15 at 8 28 14 AM" src="https://user-images.githubusercontent.com/2507232/207871135-fa5a1f0b-afba-44cf-ae3d-aa650f9dfdd3.png">

**Comment by YolineB** [comment]
Issue looks to be corrected, see image below.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/92892101/217129045-2bffcd0f-7973-42f1-a622-09c8d96ce18f.png">
