### ISSUE TITLE
Event Form Submission: Image Upload - Not visible on dark mode

### ISSUE THREAD

**Issue by Rohanfizz** [data-umbrella/event-board-web#311]
![Screenshot (487)](https://user-images.githubusercontent.com/50175798/207898106-5de6458f-37f4-4d9d-bd97-d55624222a5b.png)
![Screenshot (488)](https://user-images.githubusercontent.com/50175798/207898148-b6ee1ed3-4f41-4019-b9ee-ecc80b91a590.png)

**Comment by jtorreggiani** [comment]
Looks like this issue was resolved. Closing this issue.
