### ISSUE TITLE
Language should display name

### ISSUE THREAD

**Issue by symeneses** [data-umbrella/event-board-web#312]
En event details, the languages are listed with codes and not with the name. Also, the region looks like a code, not a description or name.

Design:
<img width="606" alt="Screen Shot 2022-12-15 at 10 31 59 AM" src="https://user-images.githubusercontent.com/12284951/207901460-cfbe909c-8ae1-4e1e-a91a-a7555f793b59.png">

Current view:
<img width="1116" alt="Screen Shot 2022-12-15 at 10 31 01 AM" src="https://user-images.githubusercontent.com/12284951/207901532-9b93797c-6c02-43b0-bf95-7c8c5bd60aae.png">

**Comment by reshamas** [comment]
This is now showing the language:  "English" instead of "en"

Closing this issue.

<img width="1095" alt="Screen Shot 2023-03-14 at 2 22 58 PM" src="https://user-images.githubusercontent.com/2507232/225101618-533942ae-4541-4556-8737-e326e7e62a83.png">
