### ISSUE TITLE
Event calendar search: not working consistently

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#314]
The event calendar search is not working consistently, particularly for past dates.

Example:  this search result is not showing any events from 2019.

<img width="1060" alt="Screen Shot 2022-12-15 at 10 42 57 AM" src="https://user-images.githubusercontent.com/2507232/207904111-bbd5a19d-4a84-476b-888f-4930449d4f74.png">

**Comment by jtorreggiani** [comment]
@reshamas, I believe this was fixed with my last backend change. The 1 event from 2019 now shows up.

![Image](https://user-images.githubusercontent.com/4009178/209453069-7961505d-dd7a-41f6-a4c3-cfaf36a39a58.png)
