### ISSUE TITLE
Update Navigation bar design

### ISSUE THREAD

**Issue by iliadeleon** [data-umbrella/event-board-web#32]
Some links from the previous design moved into drop down menus on the nav bar:

Events > Event Calendar, Post Event, Weekly Digest
Support Us > Donate, Sponsors

![NavBar_Updated](https://user-images.githubusercontent.com/88496806/181069461-f21ab344-98a1-4d3e-bc5c-0f4bc350faf7.png)

**Comment by victoriaklo** [comment]
![Screen Shot 2022-08-16 at 2 50 15 PM](https://user-images.githubusercontent.com/52011611/184991605-36c0a73d-33ba-4f19-8050-a69353636d17.png)
New updated designs to implement for DU navbar
