### ISSUE TITLE
Event Form Errors

### ISSUE THREAD

**Issue by iliadeleon** [data-umbrella/event-board-web#34]
1. Indicate required fields (*)

~~a. Name of Organization~~
b. Event Name
c. Event Description
d. Start/End Dates
e. Start/End Times
f. Time Zone
g. Event Type

2. When clicking Review CTA and user didn't fill out a required field, need scroll up to the position with error

**Comment by reshamas** [comment]
@iliadeleon Can we update this so that "Name of Organization" is optional?

**Comment by iliadeleon** [comment]
> @iliadeleon Can we update this so that "Name of Organization" is optional?

@reshamas Of course, I just thought we would want to know who is organizing the event. But if it is not necessary in order to post we can make it optional.
