### ISSUE TITLE
Event Full Page- Less Information

### ISSUE THREAD

**Issue by iliadeleon** [data-umbrella/event-board-web#35]
When users don't fill out sections on the Event Form, remove the field in the Event Full page. 
Image below to give an idea.

![Event Full Page - Less](https://user-images.githubusercontent.com/88496806/181084411-50028a02-860b-448e-ba94-b8d2b8150954.png)

**Comment by jtorreggiani** [comment]
Merged in code for conditionally rendering these data points. I think there are so additional design considerations for this task. Let's discuss how we want to tighten up this design.
