### ISSUE TITLE
Event form submission: inconsistent with data in database

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#386]
I tried to submit a hackathon event. These are my observations:  
1. I entered in the start and stop date in the form.  But, when I looked via the admin panel, the dates were not there.
2. There is no place on the form to include "paid" or "free"
3. I entered into the form the hashtag: #DataUmbrellaPyMCSprint, which does not show in the database.
4. Will the admins receive an email that a form has been submitted and should be approved?
5. In the form, I entered in "virtual" event, but in the database it does now show as being checked.

Maybe we can do an entry together to see what's going on. 

cc: @najwanan @YolineB

**Comment by YolineB** [comment]
Hi @reshamas sorry I just saw this over the weekend. I have submitted a PR for #2, "paid or free" option, and will check in with the team in regards to the other points.

**Comment by najwanan** [comment]
Hi @reshamas We can definitely walk through this together to see what's going on. Alternatively, if you want to do async, you could record a loom and drop it here. Let us know your preference.
