### ISSUE TITLE
Implement sponsors page

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#5]

**Comment by iliadeleon** [comment]
View of Sponsors page (7.26.22)
![Sponsors](https://user-images.githubusercontent.com/88496806/181041332-739d57f7-d347-4a6c-bf03-0aef0c3ec3ac.png)

**Comment by jtorreggiani** [comment]
@iliadeleon, do we have an issue for the sponsor form?

**Comment by iliadeleon** [comment]
> @iliadeleon, do we have an issue for the sponsor form?

It links back to the Contact form but there should be an option in the drop down under Topic
