### ISSUE TITLE
Implement event grid view

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#8]

**Comment by iliadeleon** [comment]
Event Grid View (7.26.22)
![Home Search Results - Grid](https://user-images.githubusercontent.com/88496806/181052817-694daa4a-6e92-4fb8-ab3f-b97e7c925825.png)

**Comment by iliadeleon** [comment]
Event Search Results- Grid View (7.26.22)
![Home Search Results - Grid](https://user-images.githubusercontent.com/88496806/181054144-98950b58-003c-4f39-b2bc-44614cb8423c.png)

**Comment by jtorreggiani** [comment]
@iliadeleon, I'm going to call this one resolved since we have the responsive grid working. I'm going to create a separate issue for the loading of more results (i.e pagination or infinite loading button).
