### ISSUE TITLE
Implement Hover Pop up for an event on Calendar

### ISSUE THREAD

**Issue by iliadeleon** [data-umbrella/event-board-web#81]
<img width="434" alt="Screen Shot 2022-08-17 at 7 39 16 PM" src="https://user-images.githubusercontent.com/88496806/185262330-ca830f8c-0adc-43e5-8cec-30d3acba105e.png">

**Comment by dashcraft** [comment]
@iliadeleon is this still the plan?

**Comment by iliadeleon** [comment]
Yes as far as I know, still the plan to do this on the calendar view. Thanks.

**Comment by crystallynnvoss** [comment]
@iliadeleon how is the hover supposed to work? Should it automatically close when you move the mouse off the event?

**Comment by iliadeleon** [comment]
On hover of the event in the calendar, that little pop up snapshot will come up. In the snapshot you can see the event date and time and easily access the event page. Let me know if you need more clarification, I can jump on a call with you.

**Comment by dashcraft** [comment]
@iliadeleon there are two interactions

on:mouseover (hover)
on:mouseoff (moving away from hovered item)

Do you want the effect to have time limit, or automatically disappear when they move their cursor away from the item?

**Comment by iliadeleon** [comment]
@dashcraft I think if we add a time limit it should be very short. If users hover over several quickly then many pop ups will be on the screen. Otherwise I dont mind it being mouseoff it disappearing.

**Comment by YolineB** [comment]
Fixed by PR #251
