### ISSUE TITLE
Make org name hyper linked styled text

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#90]

**Comment by jtorreggiani** [comment]
Move organization name from header to "EventPlanningSection" right below "Language" detail section.

Organization Name: <NAME OF ORG AS HREF>
Organization Name: <a href="http://linuxfoundation.org>Linux Foundation</a>

**Comment by YolineB** [comment]
PR for this issue https://github.com/data-umbrella/event-board-web/pull/219

**Comment by Saige243** [comment]
lgtm!
