### ISSUE TITLE
Make code of conduct a hyper link label

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#91]
Tasks:

- [x] Link code of conduct page
- [ ] In event details, have code of conduct hyper link to organization's code of conduct page
- [ ] Have links open to new tab

Eg:

![Image](https://user-images.githubusercontent.com/92892101/196290203-f2c376ee-1b54-4020-8a92-f8f73d5e4d26.png)

Code of Conduct URL : https://www.aacl2022.org/code-of-conduct should look like [AACL2022 Code of Conduct](https://www.aacl2022.org/code-of-conduct)

**Comment by Saige243** [comment]
Looks great!
