### ISSUE TITLE
Add copy for how much to donate for a feature event

### ISSUE THREAD

**Issue by jtorreggiani** [data-umbrella/event-board-web#94]
We are going to start with a $100. Sync with @iliadeleon about adding copy to this section.

**Comment by iliadeleon** [comment]
This okay? Or something else? <img width="654" alt="Screen Shot 2022-08-26 at 6 20 46 PM" src="https://user-images.githubusercontent.com/88496806/186997986-39204386-00c9-4047-8c8a-2b51ddb0e5ca.png">

**Comment by iliadeleon** [comment]
Guess it should be $1-$99 General Donation and $100+ Featured Event

**Comment by iliadeleon** [comment]
![Screen Shot 2022-11-04 at 10 36 35 AM](https://user-images.githubusercontent.com/88496806/200001521-dbbee58f-f35f-411d-8ad6-f6f02c61cc49.png)
![Screen Shot 2022-11-04 at 10 36 26 AM](https://user-images.githubusercontent.com/88496806/200001537-de96e1dc-cccb-4d53-bdca-16560ce32996.png)
