### ISSUE TITLE
Canva account

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#95]
@iliadeleon @jtorreggiani 

Information on Canva Pro account:  
https://www.canva.com/canva-for-nonprofits/

**Comment by reshamas** [comment]
@jtorreggiani will provide dimensions for rectangle image.
@reshamas will do a couple of example Canva cards.

**Comment by YolineB** [comment]
@reshamas, @jtorreggiani, @iliadeleon Are we still interested in using Canva?

**Comment by YolineB** [comment]
From Joe, 10/17: this task was for getting images ready for demo, new ticket needed to resize images for app

**Comment by reshamas** [comment]
I recommend that SPEC get the free Canva account for non-profits.
However, it's a recommendation, and up to the org (SPEC), if you want to go to through the process.
