### ISSUE TITLE
Add links to the about us page for DU and SPEC

### ISSUE THREAD

**Issue by reshamas** [data-umbrella/event-board-web#99]
Page:  https://events.dataumbrella.org/about

Reshama:  
- photo:  https://github.com/reshamas/bio-and-headshot/blob/master/_reshama_shaikh.jpg
- LinkedIn: https://www.linkedin.com/in/reshamas/
- Twitter: https://twitter.com/reshamas (@reshamas)
- GitHub: https://github.com/reshamas

**Comment by reshamas** [comment]
@iliadeleon 
Can we put a screenshot from Figma here, for the order of the team members?  
Can put in order as:  Reshama, Joe, Ilia, .....

**Comment by iliadeleon** [comment]
<img width="689" alt="Screen Shot 2022-08-29 at 5 05 39 PM" src="https://user-images.githubusercontent.com/88496806/187298850-48193ce5-863e-4b90-bf75-6d289f065a58.png">

**Comment by YolineB** [comment]
This issue is duplicated in issue #226 and fixed by PR #241
